#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const h = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'output', 'history.json'), 'utf-8'));
const all = Object.values(h.crawled);
const total = all.length;
const o = all.filter(b => b.talktalkButton === 'O').length;
const x = all.filter(b => b.talktalkButton === 'X').length;
const unknown = all.filter(b => b.talktalkButton === '미확인' || !b.talktalkButton).length;
const noPid = all.filter(b => b.talktalkVerified === 'no_pid').length;
const noPidFinal = all.filter(b => b.talktalkVerified === 'no_pid_final').length;
const ocr = all.filter(b => b.talktalkVerified === 'ocr').length;
const ocrFail = all.filter(b => b.talktalkVerified === 'ocr_fail').length;
const spam = all.filter(b => b.talktalkVerified === 'spam').length;
const html = all.filter(b => b.talktalkVerified === 'html').length;
const localCheck = all.filter(b => b.talktalkVerified === 'local_check').length;
const blocked = all.filter(b => b.talktalkVerified === 'blocked').length;
const noVerified = all.filter(b => !b.talktalkVerified).length;
const withPlace = all.filter(b => b.placeUrl).length;
const entityRe = /&amp;|&lt;|&gt;|&quot;|&#39;|&apos;|&#\d+;|&#x[0-9a-fA-F]+;/;
const withEntity = all.filter(b => entityRe.test(b.name || '')).length;
const longName = all.filter(b => b.name && b.name.length > 50 && b.talktalkVerified !== 'spam').length;
const knownPidNoPid = all.filter(b => b.talktalkVerified === 'no_pid' && b.placeUrl && /\/\d{5,}$/.test(b.placeUrl)).length;

console.log('='.repeat(60));
console.log('  현재 history.json 전체 통계');
console.log('='.repeat(60));
console.log('전체 업체수:', total);
console.log();
console.log('-- 톡톡 버튼 상태 --');
console.log('  O:', o);
console.log('  X:', x);
console.log('  미확인:', unknown);
console.log('  톡톡 보유율:', (o / Math.max(1, o + x) * 100).toFixed(1) + '%');
console.log();
console.log('-- 검증 방법별 --');
console.log('  ocr:', ocr);
console.log('  html:', html);
console.log('  local_check:', localCheck);
console.log('  ocr_fail:', ocrFail);
console.log('  blocked:', blocked);
console.log('  spam:', spam);
console.log('  no_pid:', noPid);
console.log('  no_pid_final:', noPidFinal);
console.log('  미검증:', noVerified);
console.log();
console.log('-- 미처리 현황 --');
console.log('  placeUrl 보유:', withPlace, '/', total);
console.log('  placeUrl있는 no_pid (OCR 대상):', knownPidNoPid);
console.log('  HTML 엔티티 포함:', withEntity);
console.log('  이름 50자 초과 (미스팸처리):', longName);
console.log();
const processed = o + x + spam + noPidFinal;
console.log('-- 처리율 --');
console.log('  처리 완료:', processed, '/', total, '(' + (processed / total * 100).toFixed(1) + '%)');
console.log('  미처리:', total - processed);
